# Generated by Django 6.0 on 2025-12-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('razon_social', models.CharField(max_length=250)),
                ('tipo_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('segmento', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(blank=True, max_length=150, null=True)),
                ('secuencia', models.BigIntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_factor', models.CharField(max_length=32, unique=True)),
                ('descripcion_factor', models.TextField(blank=True, null=True)),
                ('tipo_valor', models.CharField(default='NUMERIC', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_instrumento', models.CharField(blank=True, max_length=80, null=True)),
                ('mercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mercado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia_evento', models.BigIntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ingreso_por_montos', models.BooleanField(default=False)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('es_isfut', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Vigente', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evento')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instrumento')),
                ('mercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mercado')),
                ('usuario_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to='core.usuario')),
                ('usuario_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_modificadas', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='core.calificaciontributaria')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.factor')),
            ],
            options={
                'unique_together': {('calificacion', 'factor')},
            },
        ),
    ]
