# Generated by Django 6.0 on 2025-12-06 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mercado')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(default=2025)),
                ('fecha_pago', models.DateField()),
                ('secuencia', models.IntegerField(default=0, help_text='Secuencia del evento de capital.')),
                ('origen', models.CharField(choices=[('Manual', 'Ingreso Manual'), ('Carga', 'Carga Masiva'), ('Sistema', 'Sistema Central')], default='Manual', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valor_historico', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('factor_actualizacion', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('factor_08', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F08: Con Crédito IDPC')),
                ('factor_09', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F09: Créditos Acum. 2016')),
                ('factor_10', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F10: IDPC Voluntario')),
                ('factor_11', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F11: Sin derecho a crédito')),
                ('factor_12', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F12: Rentas RAP')),
                ('factor_13', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F13: Otras rentas percibidas')),
                ('factor_14', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_15', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_16', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_17', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_18', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_19', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_20', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F20: ISFUT Ley N°20.780')),
                ('factor_21', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F21: Rentas hasta 31.12.1983')),
                ('factor_22', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F22: Rentas Exentas IGC/IA')),
                ('factor_23', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_24', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_25', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_26', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_27', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_28', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_29', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_30', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F30: Rentas Afectas c/Derecho')),
                ('factor_31', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_32', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_33', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F33: Crédito por IPE')),
                ('factor_34', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_35', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_36', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_37', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F37: Otros Créditos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(help_text='Aislamiento de datos: Sólo el dueño puede ver/editar.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Corredor Asociado')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrumento')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'unique_together': {('instrumento', 'ejercicio', 'secuencia', 'usuario')},
            },
        ),
    ]
