# Generated by Django 6.0 on 2025-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calificaciontributaria_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='monto_historico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Histórico'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='rut_propietario',
            field=models.CharField(default='0-0', help_text='RUT de la persona o empresa dueña del dividendo', max_length=12, verbose_name='RUT Propietario'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Actualizado'),
        ),
    ]
